# Generated by Django 3.2.18 on 2023-02-19 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hastane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Hastane Adı')),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Kodu')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('web', models.URLField(blank=True, verbose_name='Website')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='Email Adresi')),
                ('owner', models.IntegerField(default=1, verbose_name='Venue Owner')),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Istek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tibbi_malzeme_ilac_asi', models.CharField(max_length=120, verbose_name='Tibbi Malzeme / Ilac / Asi')),
                ('kisisel_gereksinimler', models.CharField(max_length=120, verbose_name='Event Date')),
                ('hastanenin_altyapi_gereksinimleri_sorunlari', models.TextField(blank=True)),
                ('hastanede_saglik_calisani_gereksinimi', models.TextField(blank=True)),
                ('temel_gereksinimler', models.TextField(blank=True)),
                ('ailevi_gereksinimler', models.TextField(blank=True)),
                ('diger_gereksinimler', models.TextField(blank=True)),
                ('mesaj_kutusu', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False, verbose_name='Aprroved')),
                ('hastane_adi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='istekler.hastane')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
