# Generated by Django 3.2.18 on 2023-02-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('istekler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='istek',
            old_name='kullanici',
            new_name='kullanici_adi',
        ),
    ]
